### ISSUE TITLE
Minor error in a code example

### ISSUE THREAD

**Issue by LastLeaf** [gfxfundamentals/webgpufundamentals#13]
https://github.com/gfxfundamentals/webgpufundamentals/blob/95c376684c687bd5ae8c4b1a729ab64638adf2db/webgpu/lessons/webgpu-wgsl.md?plain=1#L224

`let d = a * b;  // d is vec4f(6, 12, 21, 32)`

The expected value should be `(5, 12, 21 32)` ?

**Comment by greggman** [comment]
Thanks! https://github.com/gfxfundamentals/webgpufundamentals/commit/30c036e1b9d0b58068f24092de482a4d52117f83
