### ISSUE TITLE
Video texture example not working

### ISSUE THREAD

**Issue by mendes5** [gfxfundamentals/webgpufundamentals#22]
I got stuck on the [video texture part](https://webgpufundamentals.org/webgpu/lessons/webgpu-importing-textures.html) for quite some time, I tought it was a problem with my code but looking on the site, it also doesn't work there.

Tested on Chrome 113.0.5672.93 on Windows but got the same issues on an Macbook as well and two other machines, so not sure if it is an driver issue.

```
Uncaught (in promise) DOMException: Failed to execute 'copyExternalImageToTexture' on 'GPUQueue': Copy rect is out of bounds of external image
``` 

Funny enough, you can get it to work by subtracting one from the video size for some reason:

```
  function getSourceSize(source) {
    return [
      source.videoWidth - 1 || source.width,
      source.videoHeight - 1|| source.height,
    ];
  }
```

So may it be a Google Chrome issue? I was unable to run WebGPU on Firefox so no luck there...

**Comment by greggman** [comment]
Thanks for the bug report. Sorry it's not working.

I think this is a bug in Chrome. If I try [Chrome Canary](https://www.google.com/chrome/canary/) the example works

I think this issue fixed it: https://bugs.chromium.org/p/dawn/issues/detail?id=1694

So hopefully the fix will ship soon.
