### ISSUE TITLE
Maybe another language in addition to JS

### ISSUE THREAD

**Issue by pythops** [gfxfundamentals/webgpufundamentals#32]
Hi,

I'm wondering if it's possible to expand this tutorial and add other examples using another language (rust for example) so it's not centered only around JS

Thanks

**Comment by tiye** [comment]
If you wish

Rust https://sotrh.github.io/learn-wgpu/
C++ https://eliemichel.github.io/LearnWebGPU/

**Comment by pythops** [comment]
Thanks
